# Generated by Django 4.2.26 on 2025-11-21 08:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Form",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Form description shown to users"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly version of the title", unique=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether users can access this form"
                    ),
                ),
                (
                    "allow_multiple_submissions",
                    models.BooleanField(
                        default=True,
                        help_text="Allow same user to submit multiple times",
                    ),
                ),
                (
                    "email_notification",
                    models.EmailField(
                        blank=True,
                        help_text="Email to send form submissions to",
                        max_length=254,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Form",
                "verbose_name_plural": "Forms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(help_text="Label shown to users", max_length=200),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Input"),
                            ("email", "Email"),
                            ("number", "Number"),
                            ("textarea", "Text Area"),
                            ("select", "Dropdown"),
                            ("checkbox", "Checkbox"),
                            ("radio", "Radio Button"),
                            ("date", "Date"),
                            ("phone", "Phone Number"),
                        ],
                        max_length=20,
                    ),
                ),
                ("help_text", models.CharField(blank=True, max_length=500)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="Options separated by commas (for dropdown/radio)",
                    ),
                ),
                ("placeholder", models.CharField(blank=True, max_length=200)),
                (
                    "pattern",
                    models.CharField(
                        blank=True,
                        help_text="Regex pattern for validation",
                        max_length=500,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Field",
                "verbose_name_plural": "Form Fields",
                "ordering": ["form", "order"],
                "unique_together": {("form", "label")},
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("user_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, help_text="Browser info")),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="forms.form",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Submission",
                "verbose_name_plural": "Form Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="FormSubmissionData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_label", models.CharField(max_length=200)),
                ("value", models.TextField()),
                (
                    "field",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="forms.formfield",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="forms.formsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Submission Data",
                "verbose_name_plural": "Form Submission Data",
            },
        ),
    ]
