# Generated by Django 4.2.26 on 2025-11-10 08:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("whatsapp", models.CharField(blank=True, max_length=50)),
                ("working_hours", models.CharField(blank=True, max_length=200)),
                (
                    "map_embed",
                    models.TextField(blank=True, help_text="Google Maps embed code"),
                ),
            ],
            options={
                "verbose_name": "Contact Information",
                "verbose_name_plural": "Contact Information",
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="homepage/"),
                ),
                ("content", ckeditor.fields.RichTextField()),
                ("welcome_section", ckeditor.fields.RichTextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home Page",
                "verbose_name_plural": "Home Page",
            },
        ),
        migrations.CreateModel(
            name="InformationPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="About Us", max_length=200)),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "mission",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Mission statement"
                    ),
                ),
                (
                    "vision",
                    ckeditor.fields.RichTextField(
                        blank=True, help_text="Vision statement"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="information/"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Information Page",
                "verbose_name_plural": "Information Page",
            },
        ),
    ]
