# Generated by Django 4.2.26 on 2025-11-10 08:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="subtitle",
            field=models.CharField(
                blank=True,
                default="Your trusted partner for eco-friendly and sustainable solutions",
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="title",
            field=models.CharField(default="Welcome to KiyaGreen", max_length=200),
        ),
    ]
