# Generated by Django 4.2.24 on 2026-01-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_homepage_content_alter_homepage_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactinfo",
            name="wechat_qr",
            field=models.ImageField(
                blank=True,
                help_text="WeChat QR code image",
                null=True,
                upload_to="contact/",
            ),
        ),
    ]
