# Generated by Django 4.2.26 on 2025-11-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFQRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField(blank=True)),
                (
                    "subject",
                    models.CharField(
                        blank=True, help_text="Request subject", max_length=300
                    ),
                ),
                (
                    "message",
                    models.TextField(help_text="Additional details or requirements"),
                ),
                (
                    "quantity",
                    models.IntegerField(default=1, help_text="Quantity needed"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Optional attachment (specs, drawings, etc.)",
                        null=True,
                        upload_to="rfq/attachments/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("quoted", "Quoted"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal notes for admin"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfq_requests",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFQ Request",
                "verbose_name_plural": "RFQ Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RFQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Product name if not in database", max_length=300
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                ("specifications", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
                (
                    "rfq",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="rfq.rfqrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFQ Item",
                "verbose_name_plural": "RFQ Items",
            },
        ),
    ]
