# Generated by Django 4.2.26 on 2025-11-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Recommended: 300x300px (Square 1:1), JPEG/WebP, under 100KB",
                null=True,
                upload_to="categories/",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                help_text="Recommended: 800x800 to 1200x1200px (Square 1:1), JPEG/WebP, under 500KB",
                upload_to="products/",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Descriptive text for accessibility",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                help_text="Recommended: 800x800 to 1200x1200px (Square 1:1), JPEG/WebP, under 500KB",
                upload_to="products/gallery/",
            ),
        ),
    ]
