# Generated by Django 4.2.26 on 2026-02-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_image_alter_product_main_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.CharField(
                blank=True, help_text="Company or manufacturer name", max_length=200
            ),
        ),
    ]
